name: Test CI

on: push

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3 # v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build workspaces
        run: yarn build

      - name: Run Test
        run: yarn test:coverage

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
