name: Test CI

on: push

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3 # v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build workspaces
        run: pnpm build
